# Generated by Django 2.2.12 on 2022-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_djelatnik_oib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djelatnik',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
